platform :ios, '8.0'

target 'PomodoroApp' do

# TODO 在公司网试一下,不行就不用这个appcenter了.以后再用!!!
#
# Use the following line to use App Center Analytics and Crashes.
#   pod 'AppCenter'

# Use the following lines if you want to specify which service you want to use.
#   pod 'AppCenter/Analytics'
#   pod 'AppCenter/Crashes'

	pod 'WechatOpenSDK'
#	pod 'AppCenterReactNativeShared'
end
