platform :ios, '8.0'

target 'PomodoroApp' do

# TODO 在公司网试一下,不行就不用这个appcenter了.以后再用!!!
#
# Use the following line to use App Center Analytics and Crashes.
#   

# Use the following lines if you want to specify which service you want to use.
#   pod 'AppCenter/Analytics', '~> 1.0.1'
#   pod 'AppCenter/Crashes', '~> 1.0.1'

	pod 'WechatOpenSDK'
#	pod 'AppCenterReactNativeShared', '~> 1.0.1'
end
